// <auto-generated />
namespace FA.JustBlog.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class JustBlogDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JustBlogDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202112091409108_JustBlogDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
